graph LR
    A[Загрузка новой версии руководства из notion] --> B[Добавленно приветствие в task.txt]
    B --> C[Создание файла task.txt]
    C --> D[Изменены ссылки в README.md]
    D --> E[RESTRUCTURED]
    D --> F[Добавить путь к файлу VCS в файле README.md]
    E --> G[Начинать перелинковку в файле README.MD]
    G --> H[Закончить перелинковку в файле README.MD]
    H --> I[Финализировать перелинковку в файле README.MD]
